# POST http://localhost:8080/todos
# Content-Type: application/json

# {
#   "title": "学习Gin框架",
#   "description": "今天搞定项目初始化和创建任务功能"
# }


# GET http://localhost:8080/todos


# PUT http://localhost:8080/todos/1
# Content-Type: application/json

# {
#   "title": "改一下标题",
#   "description": "描述也换一换",
#   "status": "completed"
# }

DELETE http://localhost:8080/todos/1