# POST http://localhost:8080/todos
# Content-Type: application/json

# {
#   "title": "学习Gin框架",
#   "description": "今天搞定项目初始化和创建任务功能"
# }


# GET http://localhost:8080/todos


# PUT http://localhost:8080/todos/1
# Content-Type: application/json

# {
#   "title": "改一下标题",
#   "description": "描述也换一换",
#   "status": "completed"
# }

# DELETE http://localhost:8080/todos/1

# POST http://localhost:8080/register 
# Content-Type: application/json

# {
#   "username": "ludy",
#   "password": "123456"
# }

# POST http://localhost:8080/login
# Content-Type: application/json

# {
#   "username": "ludy",
#   "password": "123456"
# }



# GET http://localhost:8080/todos
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTAxNTkyNjQsInVzZXJfaWQiOjF9.3w28VQEhtS6mnQNdVZWohkSx_Y7A2ixpZD0lqpzXs7E
